export default function Head() {
  return (
    <>
      <title>Tailwind Dark Mode</title>
      <meta content='width=device-width, initial-scale=1' name='viewport' />
      <meta
        name='description'
        content='Generated by create nextja tailwind dark mode'
      />
      <link rel='icon' href='/favicon.ico' />
    </>
  );
}
